services:
  - type: web
    name: v-face-server
    runtime: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VFACE_ENCRYPTION_KEY
        generateValue: true
      - key: DASHBOARD_URL
        value: https://v-face-dashboard.vercel.app
      - key: PLAYGROUND_URL
        value: https://v-face-playground.vercel.app

